### ISSUE TITLE
404 thrown when reading from a spreadsheet configured in the mod options

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6810] opened 2023-11-02 17:15 UTC
## Describe the bug

I created a simple mod to test adding a spreadsheet to a mod during activation (Sidebar and Extension Console). The spreadsheet dropdown renders with all of the correct sheets, but when I run the mod after, I'm seeing a 404 error: "Cannot locate the Google Drive resource. Have you been granted access?"

## To Reproduce

1. Create a mod that uses the Google Drive integration
2. Do not hardcode the spreadsheet
3. Add a mod option for a Google Sheet
4. Activate the mod in the Sidebar or Extension Console
5. Run the mod

## Actual behavior

* The notify alert shows "Error running action"
* The Page Editor logs show:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ea6a6f9bda2b4d6ee1136d7a357b7e16ccd0e37/image.png)

## Expected behavior

The mod runs successfully

## Screenshots/Loom

https://www.loom.com/share/ffa47e77e7bc43e8919e846f003cf63a?sid=dad88951-b510-4990-8dd0-0a8e6161a18a

## Desktop (please complete the following information):

- Extension Version 1.8.2-beta.6

## Additional context

Note: Opening the Page Editor to the "Lookup Google Sheet Row" brick fixes the error

**Comment by BLoe** [comment] 2023-11-02 21:18
Closing for now as I can't reproduce; I tried:
* Local dev "watch" build on `main`, activate, reactivate, deployment
* local dev "watch build on `release/1.8.2-beta.6`, activate, reactivate, deployment
* prod webpack build on `release/1.8.2-beta.6`, activate, reactivate, deployment

**Closed by BLoe** 2023-11-02 21:18 UTC
Labels: bug, release blocker
