### ISSUE TITLE
[CANT REPRODUCE] Bug: Bot list needs to populate after configuration change

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4466] opened 2022-10-14 20:08 UTC
\[This issue was auto\-generated by ProductBoard\.\]

<https://github.com/pixiebrix/pixiebrix-extension/issues/4466>

<p></p>

Description written by Ben:

There is an issue with Automation Anywhere control room integrations where the list of bots doesn't load in the brick in the page editor after making a configuration change to an existing control room integration\. You can press the reload buttons next to the fields in the page editor and pick the integration and public\/private, but the bot list never populates with anything\. The workaround fix is you have to go to the integrations page, click the 3\-dot menu for the control room integration, and click "Refresh Token"\. Then the bot list loads in the page editor\.  
<https://pixiebrix.slack.com/archives/C0436P48QHY/p1664987215405399?thread_ts=1664987215.405399&cid=C0436P48QHY>

<p></p>

<p></p>

**Comment by twschiller** [comment] 2022-10-14 20:08
Link to feature: https://pixiebrix.productboard.com/feature-board/planning/features/15783296

**Comment by BLoe** [comment] 2022-10-24 16:20
@corinnemayans I'm not really able to reproduce this issue as it happened with the AA guy at bot games. I'm not seeing the same situation where there is NO way to refresh the list from the page editor. I'm not totally sure what direction to go with this ticket at this point. Here's what I'm seeing:

https://www.loom.com/share/33c1b871008e4cbaa6e7b031b350bd9e

**Comment by corinnemayans** [comment] 2022-10-24 20:15
Can't reproduce this specific issue ("x" works to clear per Ben's Loom). Larger issue is that the Page Editor and Extension Console stay in sync real-time, but that is a larger feature, not for this bug. Since we can't reproduce the original issue, I'm adding the "can't reproduce" flag and removing the milestone, and we will leave this logged for some time to see if it comes up again, and if so, get steps to reproduce. If we don't see this again, we should close this as "won't fix".

**Closed** 2023-02-06 06:11 UTC
Labels: bug, can't reproduce
