### ISSUE TITLE
Extension Console integrations: Zapier modal cannot be closed

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7756] opened 2024-02-28 17:07 UTC
## Describe the bug

You can open it, but it stays open until a page reload

## To Reproduce

1. Go to chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/options.html#/services
2. Click on "View key" next to Zapier
3. Click "x" button

## Actual behavior

Nothing happens, no errors in console. Even when clicking outside or pressing ESC.

Only the URL changes from `#/services/zapier/` to `#/services/` 

## Screenshots/Loom

<img width="1404" alt="Screenshot 15" src="https://github.com/pixiebrix/pixiebrix-extension/assets/1402241/34cd3bf5-aa4e-4c75-94ea-fa723ba61027">

## Desktop (please complete the following information):

- Extension Version: 1.8.10-local

**Comment by fregante** [comment] 2024-02-28 17:08
## Related bug 1

If you open `chrome-extension://mpjjildhmpddojocokjkgmlkkkfjnepo/options.html#/services/zapier/` directly:

- the modal doesn't open
- the View Key button doesn't do anything

I vote to just drop this deep-link

**Comment by brittanyjoiner15** [comment] 2024-04-22 15:22
Upvoting this since I came across a user that hit it last week

**Comment by twschiller** [comment] 2024-06-16 15:23
@brittanyjoiner15 is this still happening for you? I'm not able to reproduce either problem locally or on the CWS version

**Comment by brittanyjoiner15** [comment] 2024-06-17 14:39
@twschiller interesting, not happening for me anymore either. must've gotten fixed with something at some point!

**Comment by BLoe** [comment] 2024-06-17 14:50
I don't remember the specific PR but I think I may have fixed this at some point... 🤔

**Closed** 2024-06-17 14:56 UTC
Labels: bug, user experience, triage
