### ISSUE TITLE
Field annotations (e.g., warnings) not displaying for Customer Form namespace field

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#6966] opened 2023-11-24 19:18 UTC
## Describe the bug

![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/6323fefe-a9f6-4f25-a251-c2e6523a5aed)

## To Reproduce

1. Checkout `main`
1. Create a new Sidebar Starter Brick
2. Add a custom form

## Actual behavior

1. The State Namespace field doesn't have an annotation on it
2. You can see that the annotation exists properly in the in the internal-only "state" panel

## Expected behavior

1. The State Namespace field has a warning annotation on it

## Desktop (please complete the following information):

- N/A

## Triage

Can be confusing if you're making a sidebar panel and can't figure out why/where there's a warning in your mod

## Discussion

The path of the annotation and path associated with the field are consistent:

- Path of the annotation is: `extension.blockPipeline.0.config.body.0.children.2.children.0.children.0.config.pipeline.__value__.0.config.storage.namespace`
- Path of the field in the UI is `extension.blockPipeline.0.config.body.0.children.2.children.0.children.0.config.pipeline.__value__.0.config.storage.namespace`

The error annotation is collapsed with no content:
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/3e95879b-f310-490e-827e-c7aa1830eb8f)

There appears to be something wrong with that field in particular, maybe because it's a nested field?
![image](https://github.com/pixiebrix/pixiebrix-extension/assets/1879821/b8f03413-0cbe-4fa3-8f55-0eca22c0790b)

**Comment by grahamlangford** [comment] 2023-12-22 15:36
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/7167

**Closed by grahamlangford** 2023-12-22 15:36 UTC
Labels: bug, page editor, analysis
