### ISSUE TITLE
Accept invitation link in Extension Console doesn't work (takes you to Create Team page in admin console)

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#5207] opened 2023-02-17 16:11 UTC
Context
---
- The extension links to `/team` which redirects to the create team page if you're not already a member of a team
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1676649943368949

Discussion
---
- We likely need it to link to the `/` root page of the Admin Console, which will show your pending invitations
- InvitationAlert component in the app is only shown on the main Admin Console page anyway: https://github.com/pixiebrix/pixiebrix-app/blob/6aedae0cf62060de65c3114f3a1164d43a472225/pixiebrix-app/src/pages/ExtensionPage.tsx#L78-L78

Resources
---
- InvitationBanner: https://github.com/pixiebrix/pixiebrix-extension/blob/bfb1eefd9bde6c4f1fd98598ab5dccaa517e68f4/src/options/pages/InvitationBanner.tsx#L27-L27

**Comment by corinnemayans** [comment] 2023-02-27 18:13
I think this is a duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/5242
@BrandonPxBx - will you confirm?

**Comment by BrandonPxBx** [comment] 2023-02-27 19:05
@corinnemayans  - Yes, this is a duplicate.

**Comment by corinnemayans** [comment] 2023-03-01 23:43
This one was opened first, the other one came from product board and Misha has worked on that one, so I'm closing this one as the dup.

**Closed by corinnemayans** 2023-03-01 23:43 UTC
Labels: bug, next
