### ISSUE TITLE
Page Editor is not finding existing foundations

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#1512] opened 2021-09-27 17:09 UTC
`Use Existing...` buttons are disabled for all foundation types right now on `main`:

![image](https://user-images.githubusercontent.com/2801308/134954406-de61aff9-f22c-4139-bb4d-01297d8a6a56.png)

**Comment by twschiller** [comment] 2021-09-28 20:55
Can't reproduce and it's working for @BLoe now, so closing. Will re-open if it comes up during QA of 1.4.0

**Closed by twschiller** 2021-09-28 20:55 UTC
Labels: bug, priority, page editor
