### ISSUE TITLE
Error when using "Close Tab" brick on target window

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2417] opened 2022-01-17 18:01 UTC
Steps to reproduce:
1. Create an extension that brick that a) opens a new tab, b) calls close tab using `window: target`
2. When you run the extension, the tab will open/close. And an error message will appear on the main tab that triggered the execution

Resources:
- Demo/discussion: https://pixiebrix.slack.com/archives/C02CN01JXAA/p1642441909005000?thread_ts=1642441808.004700&cid=C02CN01JXAA

Workaround:
- Use two extensions: one for the button, and one to close the other tab

Possible Fix:
- Have the Close Brick tab throw a special exception (e.g., TabClosed) before actually closing the tab. That way, the main tab gets a response. It'd just need to ignore that special exception type. We do something similar with CancelError, where we show special notifications and don't report it to error telemetry

**Comment by fregante** [comment] 2022-01-17 23:37
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/2051

**Closed** 2022-01-18 12:48 UTC
Labels: bug, runtime
