### ISSUE TITLE
Allow teams to restrict access to certain URLs unless PixieBrix is authenticated

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#7435] opened 2024-01-25 22:15 UTC
https://www.notion.so/pixiebrix/Allow-teams-to-restrict-access-to-certain-URLs-unless-PixieBrix-is-authenticated-e3b29cdfa553424bb5abc8aee79c4d1c?pvs=4

**Comment by grahamlangford** [comment] 2024-01-29 17:50
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/7474

**Closed by grahamlangford** 2024-01-29 17:50 UTC
Labels: customer, enterprise
