### ISSUE TITLE
HTTP bricks spontaneously self assigning services

### ISSUE THREAD

**Issue by 4626433** [pixiebrix/pixiebrix-extension#1821] opened 2021-11-05 02:22 UTC
HTTP bricks made in the page editor that do not have a chosen service sometimes gain the first selectable service, usually causing an error. When this happens they still show no service selected in the page editor. Replacing the affected brick with a new identical brick temporarily fixes this issue. Currently a workaround is using a service with no properties or authentication parameters.

**Comment by twschiller** [comment] 2021-11-06 19:04
Related: https://github.com/pixiebrix/pixiebrix-extension/issues/1818

**Comment by twschiller** [comment] 2021-11-10 19:06
Could you give some hints on how I might reproduce this?

I’m able to hit https://hn.algolia.com/api/v1/search?query=foo&tags=story using the `@pixiebrix/get` brick in the Page Editor

Things I've tried, but can't reproduce the issue:
- Clicking into the select service and then clicking out with selecting anything
- Clicking between bricks
- Saving the extension, closing page editor, and re-opening to the brick

**Closed** 2021-11-14 13:23 UTC
Labels: bug, can't reproduce
