### ISSUE TITLE
Target for HANDLE_MENU_ACTION not found and Page Editor cannot connect to page

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4863] opened 2022-12-22 19:35 UTC
Context
---
- Observed in version 1.7.15
- https://pixiebrix.slack.com/archives/C0436P48QHY/p1671737446508829?thread_ts=1671652087.068049&cid=C0436P48QHY

Steps to Reproduce
---
- Activate https://www.pixiebrix.com/marketplace/ca72c199-72fb-4871-adce-a19ad251022b/linkedin-comment-templates/
- Clear your browser cache
- Visit www.linkedin.com, and then right click context menu

Discussion
---
- Looks like a potential race condition with the content script being ready
- No error appears in the extensions log. Failed context menu handler action in the background page don't appear to be correlated with a blueprint/extension

Screenshots
---
![image](https://user-images.githubusercontent.com/1879821/209212823-db54e880-de58-4095-a4f5-caa8dbd3082a.png)

**Comment by fregante** [comment] 2022-12-26 05:49
I tried several times and could not reproduce this. I saw it before before but it's inconsistent.

From the log, it seems that the content script has been injected successfully. Could you enable the messenger logs via `WEBEXT_MESSENGER_LOGGING=true`?

**Comment by fregante** [comment] 2022-12-26 06:51
https://github.com/pixiebrix/webext-messenger/blob/eae4ffb28fb0ec9cc4e0ef88b0aeceafecf29a4f/source/sender.ts#L126-L127

Following the logic in the messenger, it does seem that `onMessage` was never called in the content script. However that that sequence of `ensureContentScript` cannot happen without the explicit "ready notification" from the content script:

https://github.com/pixiebrix/pixiebrix-extension/blob/ae55fca9e0c610c801f05107f2cde021db09ef0f/src/background/contentScript.ts#L119-L124

which happens in the CS core, after Messenger is registered:

https://github.com/pixiebrix/pixiebrix-extension/blob/ae55fca9e0c610c801f05107f2cde021db09ef0f/src/contentScript/contentScriptCore.ts#L65-L66

Any ideas of what might be happening?

A couple of extra things to note in your logs:

- `ensureContentScript` is requested again after the error, but it never reports `ready`. By that time it should already be "already exists and is ready" 🤔 
	- does that related to a different tab? each target in the screenshot is collapsed into `object` so it's hard to say
	- why did it not time out?
- "already exists or will be injected automatically" likely means that we already had permissions on the host and by the time context menu is run, the CS could already have been there.

**Comment by twschiller** [comment] 2023-01-02 16:52
@fregante I paired with Mike on this today. It's still happening reliably when he's using a fresh tab

The other thing I noticed is that the Page Editor is not able to connect to the page

What's weird is that the Chrome Dev Tools console does show the contentScript being initialized and there were now error (although I didn't double-check that the initialization debug messages were from the top-level frame)

I'm going to have @MMirandi upgrade to the latest beta. I'll also dig into your comment above today

**Comment by twschiller** [comment] 2023-01-02 19:24
Expanded background script 

Seems like the script is reporting itself as ready before the handler is registered. Or the handlers are somehow getting reset

![image](https://user-images.githubusercontent.com/1879821/210271549-6084487a-9739-4cda-9aab-68d1c5a6dc59.png)

![image](https://user-images.githubusercontent.com/1879821/210271594-10c26eeb-c2e2-4cdd-81a9-8bd93023ad1a.png)

**Comment by twschiller** [comment] 2023-01-02 21:34
@fregante I'm working on a PR. I'm pretty sure it's due to `background/contentScript` not considering the sender of the ENSURE_CONTENT_SCRIPT_READY message, so there's a race especially if there are frames on the page

**Comment by twschiller** [comment] 2023-01-03 00:00
The PR didn't solve the problem for @MMirandi: https://github.com/pixiebrix/pixiebrix-extension/pull/4939

**Comment by fregante** [comment] 2023-01-03 01:41
Question: Does @MMirandi have a LinkedIn host permission? This changes where we need to look for the issue.

If it has a permission already, then the injection should not be a problem, or rather the problem could be in my dynamic injection module, not here. Even if "ensure content script ready" fires too early, HANDLE_MENU_ACTION will still retry several times.

Even with the changes from the latest PR, the message specifically targets the top frame, which we shouldn't have a problem injecting into.

If the issue is indeed the redirect, then I can look into that as part of the dynamic injection module. There's little chance that the redirect affects injections requested _after_ the page load (which is when the user clicks the context menu)

**Comment by twschiller** [comment] 2023-01-03 01:47
Yes, he has the host permission and it's webext-dynamic-content-injection that's doing the injection:

![image](https://user-images.githubusercontent.com/1879821/210290600-13e00495-3e44-400d-b08e-03da5c07f5cd.png)

**Comment by fregante** [comment] 2023-01-03 02:05
The thing is: `await readyNotificationPromise` is explicitly waiting for the message from contentScriptCore, so the messenger is definitely 100% "there". Your latest PR should confirm that "there" is also the correct frame, so could "there" be the wrong context? 

All in all, where else is this issue happening? Just Mike’s computer? Can PB be removed and reinstalled?

**Comment by twschiller** [comment] 2023-01-12 00:17
@fregante I paired with Mike on this -- looks like the contentScript is never getting injected on the top-level frame (the are no logs generated for top-level frame). But it is being injected in sub-frames on the page

Background page:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/1879821/211945691-377fa85d-6708-4a7d-b4be-3f9d010f2553.png">

**Comment by fregante** [comment] 2023-01-12 02:32
> the are no logs generated for top-level frame

You mean in the tab itself? Because the background page is injecting in frame 0

> looks like the contentScript is never getting injected on the top-level frame

That's interesting because that should be the easiest one to track. Can you check what's the result of `chrome.permissions.getAll(console.log)`?

I wonder if there's some deduplication issue at play

**Comment by twschiller** [comment] 2023-01-12 04:46
> You mean in the tab itself?

Correct - if I restrict Chrome to only show logs from the selected context and select the top-level PixieBrix context the logs are empty. (🤔 Although I wouldn't expect to even see the context if there was no contentScript in the top-level frame)

I have more extensions than Mike (screenshot if from me), but I'm choosing the one right below the `top` context:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/1879821/211977606-79c62bf6-f80e-44d2-9c57-1427d75a7560.png">

> Can you check what's the result of chrome.permissions.getAll(console.log)?

I'll pair with Mike tomorrow to check. He has `*://*/*` currently as his dynamic permissions. But that could be multiple permission Chrome has merged for getAll

> But that wouldn't explain why we get those "ready on frame 0"

That's correct. Only thing I could think of is if somehow one of the sub-frames causing it to fire. But that shouldn't be the case now that onReadyNotification considers the target

**Comment by twschiller** [comment] 2023-01-12 17:21
I think my screenshot was wrong, it's not actually ever getting a "ready" call:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/1879821/212133762-201cf865-289f-4629-b3d1-a9b9f4bc59ff.png">

Permissions:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/1879821/212134081-4bc1f579-2ea6-483a-9048-56596592cb72.png">

Investigation
---
- I had Mike revoke the permissions and reload the background page
- It worked once, but when he cleared the LinkedIn cookies it started happening again
- If you reload the tab it works

**Comment by twschiller** [comment] 2023-01-12 23:13
Is Chrome the one responsible for injecting into new tabs if it's already in additional permissions? I don't see any code in webext-content-scripts or webext-content-scripts for that

It's still odd that there's a contentScript context available under "top" for PixieBrix in the console context dropdown, but there's no logs for that context.

**Comment by fregante** [comment] 2023-01-13 04:37
> Is Chrome the one responsible for injecting into new tabs if it's already in additional permissions? I don't see any code in webext-dynamic-content-scripts or webext-content-scripts for that

The injection in Chrome MV2 is handled by:

1. webext-dynamic-content-scripts
2. [which calls content-script-register-ponyfill](https://github.com/fregante/webext-dynamic-content-scripts/blob/59d58ce089707144286a241b6963c66d52b63e06/index.ts#L44)
3. [which calls webext-content-scripts](https://github.com/fregante/content-scripts-register-polyfill/blob/232421e3b9ce867f7a398e455cc7e94cc8dc951c/ponyfill.ts#L62-L74) for a standardized injection

[We're using `webNavigation.onCommitted`](https://github.com/fregante/content-scripts-register-polyfill/blob/232421e3b9ce867f7a398e455cc7e94cc8dc951c/ponyfill.ts#L96-L100) which is presumably the best event available, working on a per-frame basis and not a per-tab one.

I also have automated tests in `webext-dynamic-content-scripts` in a live browser environment with this API.

Once we switch to MV3, the injection will be handled by the browser, except for `activeTab`, allowing `webext-dynamic-content-scripts` to just keep track of the permissions.


> It's still odd that there's a contentScript context available under "top" for PixieBrix in the console context dropdown, but there's no logs for that context.

Make sure you're selecting the right context, because when the extension reloads, it leaves behind multiple inactive content scripts. 

<img width="310" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/212238119-85bbf1a3-3092-497f-ba9c-7d624b76f506.png">

I think that that context also appears with a simple `chrome.tab.executeScript({code: 'true'})` which we have in some parts to the app, for example:

https://github.com/pixiebrix/pixiebrix-extension/blob/251b6d562ef723779705cccaa7eb7f2e6e78f02c/src/contentScript/ready.ts#L104:L111

That would explain why the context appears, but none of the logs do:

https://github.com/pixiebrix/pixiebrix-extension/blob/251b6d562ef723779705cccaa7eb7f2e6e78f02c/src/contentScript/contentScript.ts#L35-L48

This should also help us see whether anything was injected at all:

- #5001

**Comment by corinnemayans** [comment] 2023-01-13 23:07
Removing the milestone for now since the milestone is in the past and I'm closing out the old milestone. Please add a new milestone when ready.

**Comment by twschiller** [comment] 2023-01-14 00:10
> The injection in Chrome MV2 is handled by:

Gotcha. I had somehow overlooked the top-level register call here: https://github.com/fregante/webext-dynamic-content-scripts/blob/main/index.ts#L102

I'll pair with @MMirandi  to see if onCommitted isn't firing for the page

**Comment by fregante** [comment] 2023-01-21 10:20
Something I noticed is that the content script is loaded really late on LinkedIn and nytimes.com for example. It seems that it's not following our "document_start" request but falling back to "document_idle"

This is a particularly slow example that would certainly fall through any of our timeouts. I noticed this slowdown the last time I looked into this ticket, but given your logs I was assuming it wasn't the case here.

The videos starts after a page reload:


https://user-images.githubusercontent.com/1402241/213862509-eb5d057d-3ec3-4bd6-a74a-1295530ea11b.mov

**Comment by fregante** [comment] 2023-01-21 10:24
Well… I always assumed we had `document_start`, but we don't

https://github.com/pixiebrix/pixiebrix-extension/blob/32e4845130fefb844e310c9a30343aae56bbcf5d/src/manifest.json#L22-L29

**Comment by twschiller** [comment] 2023-01-21 14:42
> Well… I always assumed we had document_start, but we don't

Yep, we do document_idle so we don't interfere with the site performance. Most sites do their initial "idle" within a reasonable time frame. It's only a problem for certain compliance use cases on enterprise

In the future, we might consider seeing the impact of document_start, but I wouldn't prioritize it unless we're hitting problems with document_idle. (There are bigger fish to fry, especially with wrapping up sandbox and MV3 support)

**Comment by corinnemayans** [comment] 2023-03-10 21:17
Todd to pair with Mike - impacting Mike's demos. It is not generating any errors, so Todd is trying to add more logging so we can understand what is going wrong.

I'm removing the milestone.

**Comment by twschiller** [comment] 2023-05-08 13:34
Seeing some cases on 1.7.27-alpha.5 very long times to load the contentScript

![image](https://user-images.githubusercontent.com/1879821/236837704-aef60743-b8d4-462f-91ae-dc345b49bf9b.png)

**Closed** 2023-05-17 12:18 UTC
Labels: bug, priority, runtime, next
