### ISSUE TITLE
Fix HREF target in custom data table brick

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#2365] opened 2022-01-12 05:19 UTC
When using “href” in the custom data table, you have to Shift-Click to open the link. (Clicking the link tried to open in the sidebar frame)

**Comment by fregante** [comment] 2022-01-12 05:38
Related to or duplicate of:

- https://github.com/pixiebrix/pixiebrix-extension/issues/851#issuecomment-1007891912

**Closed** 2022-01-19 17:44 UTC
Labels: bug, user experience
