### ISSUE TITLE
Invalid user interface states caused by extensions installed from blueprints that have been deleted from the package registry

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#4215] opened 2022-09-01 18:08 UTC
Context
---
- https://pixiebrix.slack.com/archives/C03V12P8RED/p1662049762567929

Known Issues
---
- Page Editor sidebar shows loading indicator for the blueprint item
- Doesn't show up on the Blueprints Screen

**Comment by twschiller** [comment] 2022-11-29 22:51
Additional report: https://pixiebrix.slack.com/archives/C0436P48QHY/p1669717032060089

**Comment by corinnemayans** [comment] 2023-02-06 13:16
Another report: [](https://pixiebrix.slack.com/archives/C0436P48QHY/p1674683910843939)

**Comment by BALEHOK** [comment] 2023-02-17 16:12
Can't reproduce the issue anymore.
A [PR](https://github.com/pixiebrix/pixiebrix-extension/pull/5206) only makes uninstalling extensions more consistent.

**Comment by twschiller** [comment] 2023-02-17 16:29
> Can't reproduce the issue anymore.

For reference, in 1.7.19 we've started caching blueprints locally, and only removing blueprints from the local DB if the user switching which account they're logged in as. A side effect of this is that the primary problem discussed in this issue is not longer at play

However, there's some other behavior to fix, which @BALEHOK addressed

**Comment by corinnemayans** [comment] 2023-02-17 22:21
@twschiller - I think that we're saying that all that we need to do for this is merge Aleksandr's PR? https://github.com/pixiebrix/pixiebrix-extension/pull/5206
I moved this to Week 8, but sounds like we might be able to just close this?

**Comment by twschiller** [comment] 2023-02-17 22:35
> but sounds like we might be able to just close this?

Yes, we can close this and create a different issue for the buggy/confusing behavior that Aleksandr's PR fixes. Otherwise, we can just leave this open. Up to you

**Comment by BLoe** [comment] 2023-02-22 21:42
@twschiller @corinnemayans Aleksandr's PR #5206 is merged, but wasn't set to automatically close this issue. Should we close this now?

**Comment by corinnemayans** [comment] 2023-02-22 22:03
Closing!

**Closed by corinnemayans** 2023-02-22 22:03 UTC
Labels: bug, user experience, priority, page editor, triage, blueprints-screen, next
