### ISSUE TITLE
Background worker: Use headers.json instead of parsing the registry at runtime

### ISSUE THREAD

**Issue by fregante** [pixiebrix/pixiebrix-extension#7185] opened 2023-12-22 15:59 UTC
Would it be possible for the background page to import the pre-generated headers.json file instead of importing all the bricks and their dependencies at runtime?

This ~~complicates the build a bit (because it would require a pre-built file) but it~~ could greatly speed up the background and avoid all sorts of issues caused the transitive dependencies, like https://github.com/pixiebrix/pixiebrix-extension/pull/6774

### How

- generate headers.json and add it to git
- add a very simple CI check to ensure that the generated file matches the contents of the repo
- add `import registry from '@/headers.json'` where needed

### Related

- https://github.com/pixiebrix/pixiebrix-extension/issues/4896
	- loading headers.json should be easier than reworking the entire registry
- https://github.com/pixiebrix/pixiebrix-extension/issues/2156
	- see the list of files here

**Comment by twschiller** [comment] 2023-12-22 18:35
> Would it be possible for the background page to import the pre-generated headers.json file instead of importing all the bricks and their dependencies at runtime?

Theoretically, yes - the only uses metadata to check for permissions, version compatibility, etc. It also needs to grab the metadata from IDB in the local package registry

Related Code
---
- https://github.com/pixiebrix/pixiebrix-extension/blob/c6003ac80c9f1f3dd72b8ad3beef34b3a41f0c9d/src/background/deploymentUpdater.ts#L595-L595****

**Comment by fregante** [comment] 2023-12-28 04:08
> The transitive dependency module variables aren't a problem

They aren't until they are:

- https://github.com/pixiebrix/pixiebrix-extension/issues/7208

The service worker isn't starting because `hoverintent` is being loaded in the background and breaking it.

If we can avoid loading and running (a lot) of unnecessary code in a specific context, I think it's worth working on it. It can be improve performance and reduce future issues. This is especially true for MV3 because:

- background.js is parsed and run over and over in MV3
- background workers do not have `window`/`document`/etc, so there's always a chance some script/dependency will reference it after an unrelated update.

**Comment by twschiller** [comment] 2023-12-28 15:16
> They aren't until they are:

That's a reference to module-level variables. I agree that files that try to use the document/window in import-time code are a problem (and have been in the past for header generation)

>  I think it's worth working on it.

I agree it may make sense to work on it in the future. My point is that from a prioritization perspective, it's lower priority than the other mv3 functionality work

**Comment by fregante** [comment] 2023-12-28 15:42
> lower priority than the other mv3 functionality work

Sure. It's possible however that this might take no more than one hour of work, with sizable benefits — as long as `headers.json` already contains everything the background page needs. If it doesn't, I would just set this as low priority.

**Comment by twschiller** [comment] 2023-12-28 16:05
I believe it's going to take longer than an hour, the permissions checks require user-defined bricks to be instantiated to check permissions for auto-activated deployments:
https://github.com/pixiebrix/pixiebrix-extension/blob/157d4d0ea59edd09ee84b2044f52bc4b7ab89c55/src/permissions/deploymentPermissionsHelpers.ts#L59-L59

Given that we're now on `<all_urls>`, we might be able to drop all those permissions checks. Which I think might obviate the need for brick information

**Comment by twschiller** [comment] 2024-03-26 13:10
Closing as "wontfix", we can revisit if we encounter performance or problems caused by attempted DOM access. We haven't seen any issues during dogfooding so far

**Comment by fregante** [comment] 2024-03-29 07:40
> We haven't seen any issues during dogfooding so far

Maybe you don't associate the issues to this ticket, but here's another one in https://github.com/pixiebrix/pixiebrix-extension/pull/8073#issuecomment-2026807179

However generally they're grave enough that they are immediately seen and fixed, like in this case. But the cause isn't always immediately clear since the worker just crashes.

**Comment by twschiller** [comment] 2024-03-29 10:25
Thanks, @fregante. To see if I understand correctly, code that references the document will error potentially causing a background crash?

This ticket proposed a potential solution, but as mentioned there are considerations as to whether or not the brick implementations can be dropped from the background worker and how they might be dropped

If the cause is trying to access the document (either in a direct or transitive import), we should problem-solve that as there may be better approaches than this ticket

cc @grahamlangford

**Comment by fregante** [comment] 2024-03-29 11:14
> code that references the document will error potentially causing a background crash?


If the DOM (`window`, `document`, etc) is accessed synchronously (i.e. in the first run, outside any async code), the background worker crashes and the extension is 100% broken. This is now caught by e2e tests and immediately remediable.

If it happens later, it might just throw an error or break the specific part of the extension.




> This ticket proposed a potential solution

Yes, if it's not fit it's fine to close it. I just wanted to make sure we document the consequence of importing "everything" in the background page and occasionally reevaluate the cost of keeping the status quo.

> there may be better approaches than this ticket

Essentially I'd just like to reduce the amount of dependencies (local and npm) and avoid surprises. Using `headers.json` was just an idea. Related:

- https://github.com/pixiebrix/pixiebrix-extension/issues/4896

**Comment by twschiller** [comment] 2024-04-14 23:07
Closing as "wontfix". Will re-open as necessary

**Closed** 2024-04-16 13:45 UTC
Labels: wontfix, performance, mv3
