### ISSUE TITLE
Quick bar loses selection

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#3132] opened 2022-04-09 14:43 UTC
Steps to reproduce (to verify)
- Select text
- Hit Quick Bar short cut
- Select text passed to the extension is blank

Possible causes:
- If PixieBrix does not already have access to the page, it can't track the selection prior to hitting the keyboard shortcut. Hitting Cmd+K my unselect the text before PixieBrix has a chance to find the selection

cc @MMirandi  - I think you were seeing this?

**Comment by fregante** [comment] 2022-04-09 16:44
The logic to preserve the selection is managed by KBarToggle:

https://github.com/pixiebrix/pixiebrix-extension/blob/fd14c1096222ff7d769b95626bcc44a6f021be5f/src/components/quickBar/QuickBarApp.tsx#L60:L60

Does/should `useAutoShow` also trigger that?

https://github.com/pixiebrix/pixiebrix-extension/blob/fd14c1096222ff7d769b95626bcc44a6f021be5f/src/components/quickBar/QuickBarApp.tsx#L100-L105

**Comment by twschiller** [comment] 2022-04-10 22:42
Good catch, @fregante. I think that's worth a try. If that's the case, the buggy behavior should occur reliably on pages that PixieBrix does not have access to until the user toggles the KBar with the keyboard shortcut

**Comment by fregante** [comment] 2022-04-11 05:03
I can't replicate the issue:

https://user-images.githubusercontent.com/1402241/162667264-a07facbe-1af3-4734-af9b-11da40e0676b.mov

You can see that the content script doesn't load until I press cmd-k because that's when the (unrelated) "Action" button appears.

However I'm seeing some strange behavior when the editor is open:

- the extension doesn't appear in the dropdown
- the quickbar does not open later (cmd-k, esc, cmd-k)



https://user-images.githubusercontent.com/1402241/162668104-92f41982-77ba-4801-932b-65582f4d3986.mov



> The logic to preserve the selection is managed by KBarToggle:

I checked now: The selection controller is called even by the auto show. 

The only incorrect behavior is that it _always_ calls `restore` when the content script is loaded, because `showing === false`. That's not a problem though, because it exits immediately with a noop in that case:

https://github.com/pixiebrix/pixiebrix-extension/blob/fd14c1096222ff7d769b95626bcc44a6f021be5f/src/utils/selectionController.ts#L58-L61

**Comment by fregante** [comment] 2022-05-29 04:33
Possibly related:

- https://github.com/timc1/kbar/issues/171

**Comment by fregante** [comment] 2022-05-30 10:45
It's somewhat possible that this is entirely caused by 

- https://github.com/pixiebrix/pixiebrix-extension/issues/3510

The selection is saved into memory so if the second `selection.save()` call happens when the selection is moved, then the restoration will also not work. But then again I can't replicate it.

**Comment by fregante** [comment] 2022-08-31 07:49
Closing as resolved as this was likely a consequence of multiple kbar injections. Reopen if needed

**Closed by fregante** 2022-08-31 07:49 UTC
Labels: bug, specification required
