### ISSUE TITLE
Show “Panel is no longer available” overlay on temporary sidebar panels/forms on MV3 navigation

### ISSUE THREAD

**Issue by twschiller** [pixiebrix/pixiebrix-extension#8105] opened 2024-03-30 18:09 UTC
- https://www.notion.so/pixiebrix/Phase-2-gracefully-handle-non-SPA-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28?pvs=4#63b9bbed5b4247249e3975922040e7bc

**Comment by fregante** [comment] 2024-04-07 15:20
Duplicate of https://github.com/pixiebrix/pixiebrix-extension/issues/7369? Either one can be closed

**Comment by twschiller** [comment] 2024-04-07 16:51
Leaving both open for now. This issue is about temporary sidebar panels/forms. The other is about persistent panels and forms. They're both off of here: https://www.notion.so/pixiebrix/Phase-gracefully-handle-non-SPA-navigation-in-the-Chromium-Side-Panel-0efdedb6c1e44b088e65106202e08c28?pvs=4

**Comment by grahamlangford** [comment] 2024-04-09 20:04
Superseded by https://github.com/pixiebrix/pixiebrix-extension/issues/8209

**Comment by grahamlangford** [comment] 2024-04-09 20:05
Superseded by https://github.com/pixiebrix/pixiebrix-extension/issues/8209

**Closed by grahamlangford** 2024-04-09 20:05 UTC
Labels: bug, user experience, mv3
