### ISSUE TITLE
NPE reading mod `sharing` property on the Extension Console load

### ISSUE THREAD

**Issue by grahamlangford** [pixiebrix/pixiebrix-extension#6412] opened 2023-09-07 23:51 UTC
https://pixiebrix.slack.com/archives/C0436P48QHY/p1694119338767269

https://pixiebrix.zendesk.com/agent/tickets/353

Likely source of the error: https://github.com/pixiebrix/pixiebrix-extension/blob/655c4964cf3e4a5772f0534cf8d3236785f31f5a/src/utils/modUtils.ts#L126

**Comment by turbochef** [comment] 2023-09-11 21:43
We're unable to reproduce at the moment since we don't have enough context for how users got into this state. Mark is going to keep us posted if this happens again. In the meantime, I'm going to close it as we can't take any action.

**Comment by grahamlangford** [comment] 2023-10-10 13:11
Issue has recurred. See here: https://pixiebrix.slack.com/archives/C0436P48QHY/p1696914903488269

**Closed** 2023-10-23 17:31 UTC
Labels: bug
