### ISSUE TITLE
Lint the dependency lists for useAsyncEffect and useAsyncState

### ISSUE THREAD

**Issue by BLoe** [pixiebrix/pixiebrix-extension#8235] opened 2024-04-12 13:42 UTC
See this section on the use-async-effect docs: https://github.com/rauldeheer/use-async-effect?tab=readme-ov-file#linting-dependencies-list-using-eslint

We should try to get lint to check the dependencies for both `useAsyncEffect` and `useAsyncState`.

**Comment by grahamlangford** [comment] 2024-04-12 13:52
Duplicate of https://github.com/pixiebrix/eslint-config-pixiebrix/issues/70

**Closed** 2024-06-04 14:02 UTC
Labels: developer experience
